### ISSUE TITLE
error run fintune.py

### ISSUE THREAD

**Issue by wujindou** [linhduongtuan/BLOOM-LORA#3]
Thank you for your work ~
I got an error when running finetune.py 
ValueError: Target modules ['q_proj', 'v_proj'] not found in the base model. 
Please check the target modules and try again.

**Comment by linhduongtuan** [comment]
You can remove this model, or please refer this site https://github.com/huggingface/peft/blob/main/src/peft/mapping.py

or this issue https://github.com/linhduongtuan/BLOOM-LORA/issues/2
