### ISSUE TITLE
error run generate_bloom.py

### ISSUE THREAD

**Issue by canglangzhishuiz** [linhduongtuan/BLOOM-LORA#4]
My configuration: A100 with eight cards.

After running generate_bloom.py,  a public URL will be prompted. When I enter this URL, enter the instruction and input, and click submit, the following error is prompted: AttributeError: 'NoneType' object has no attribute 'device'.

**Comment by linhduongtuan** [comment]
@canglangzhishuiz  you can check a solution here https://github.com/tloen/alpaca-lora/issues/21
